--- #YAML:1.0
name:                GSSAPI
version:             0.26
abstract:            Perl extension providing access to the GSSAPIv2 library
license:             perl
author:              
    - Achim Grolms <perl@grolmsnet.de>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
